---
title: "MERKEZİ YÖNETİM BÜTÇE DENGESİ  VE FİNANSMANI"
author: 
  - Hilal DOĞANÇAY[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080436, [Github Repo](https://github.com/hilaldogancay/AraSinav)

# Vize Hakkında Önemli Bilgiler

\colorbox{BurntOrange}{GITHUB REPO BAĞLANTINIZI BU DOSYANIN 35. SATIRINA YAZINIZ!}

**Proje önerisi gönderimi, Github repo linki ile birlikte ekampus sistemine bir zip dosyası yüklenerek yapılacaktır. Sisteme zip dosyası yüklemezseniz ve Github repo linki vermezseniz ara sınav ve final sınavlarına girmemiş sayılırsınız.**

**Proje klasörünüzü sıkıştırdıktan sonra (`YourStudentID.zip` dosyası) 16 Nisan 2023 23:59'a kadar *ekampus.ankara.edu.tr* adresine yüklemeniz gerekmektedir.**

\colorbox{WildStrawberry}{Daha fazla bilgi için proje klasöründeki README.md dosyasını okuyunuz.}

# Giriş
Bu taslak size proje ödevinizi yazarken yardımcı olması amacıyla oluşturulmuştur. Ödevlerinizde, makalelerinizde, sunumlarınızda ve projelerinizde kullandığınız tüm bilgi kaynaklarına atıfta bulunmalısınız. Alıntı ve gönderme yapmak okuyuculara çalışmanızda kullandığınız/başvurduğunuz  kaynaklara ulaşma imkanı sağlar. **Her ne kadar kendi sözlerinizi kullanıyor olsanız da, başkalarına ait fikirleri çalışmanızda aktarıyorsanız bu fikirlerin kaynağını belgelemek zorundasınız. Aksi takdirde akademik intihal yapmış olursunuz.** Yazım konusunda @aydinonat:2007'ye başvurabilirsiniz. 


Proje ödevinizde yer alan başlıkların bu metinde yer alan başlıkları kesinlikle içermesi gerekmektedir (doğal olarak ilk bölüm başlığı hariç). Burada kullanılan başlıklar haricinde farklı alt başlıklar da kullanabilirsiniz. Projenizi yazarken bu dosyayı taslak olarak kullanıp içeriğini projenize uyarlayınız.

## Çalışmanın Amacı
Son 10 yılın Merkezi Yönetim Bütçe Dengesi ve Finansmanı İstatistiklerini analiz ederek, bütçe dengesi ile gelir ve gider kalemleri arasındaki ilişkileri inceleyen bir araştırma yapmayı amaçlıyorum.Kullanacağım veri setini T.C Hazine Ve Maliye Bakanlığı ([T.C Hazine ve Maliye Bakanlığı](https://www.hmb.gov.tr/kamu-finansmani-istatistikleri))
Bütçe Finansmanı İstatistikleri başlığı altında buldum. Veri setimin adı Merkezi Yönetim Bütçe Dengesi ve Finansmanı. Bulduğum veri setinde bulunan gözlem sayısı 64, değişken sayısı 13. Gözlemler bütçe gelirleri, bütçe harcamaları bütçe faiz dışı dengesi, bütçe dengesi, bütçe nakit dengesi, bütçe finansmanı gibi ana başlıklardan oluşuyor. Değişkenler de aylardan ve bunların toplamından oluşuyor.


## Literatür 
Bu araştırma, 2000-2013 dönemi içinde MENA seçili ülkelerde büyüme, verimlilik ve hükümet bütçe açığının etkisini inceleyerek, ekonomik büyüme, enflasyon, işgücü verimliliği ve bütçe açığı arasındaki ilişkileri ortaya koymuştur. Bu araştırmaya göre hükümet bütçe açığının ekonomik büyüme ile negatif korelasyonu da sürdürülmektedir.[@arjomand2016growth] Araştırma vergilendirme yapısının ve kamu harcamalarının sürekli durum büyüme hızını etkileyebileceği konusundaki endojen büyüme modellerinin tahminlerini desteklemekte ve Barro modeline güçlü bir destek sunmaktadır.Özellikle bozucu vergilendirme büyümeyi azaltırken, bozucu olmayan vergilendirme etkilemez; ve üretken kamu harcamaları büyümeyi artırırken, üretken olmayan harcamalar etkilemez.[@kneller1999fiscal] Makaleye göre Türkiye'de bütçe açıkları ve reel döviz kuru arasındaki etkileri 2006 verileri kullanılarak analiz edilmiştir ama bütçe açığı ve reel döviz kuru arasında nedensellik ilişkisi bulunmamıştır.[@huseyin23turkiye] Bu çalışmada devletin 2006-2020 dönemindeki vergi harcamaları ele alınarak yapılmış ve vergi kayıpları incelenmiş. Devlet vergiler ve vergi harcamalarıyla teşvik edici etkiler yaratır ama bu çalışmanın sonucunda özellikle 2017 yılı ve sonrasınartış oranı çok yüksektir. Dolayısıyla vergi harcamalarındaki artışın bütçe gelirlerinde yarattığı kayıp miktarı da yükseliştedir.[@uygunprof]


**_Taslakta bu cümleden sonra yer alan hiçbir şey silinmemelidir._**

\newpage
# Kaynakça {#references}
<div id="refs"></div>
(https://www.hmb.gov.tr/kamu-finansmani-istatistikleri)
(chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.researchgate.net/profile/Esra-Uygun/publication/350994922_Turkiye'de_Vergi_Harcamalarinin_Gelisimi_ve_Gelir_Kaybi_Acisindan_Degerlendirilmesi_2006_-2020_Yillari/links/607e93b12fb9097c0cf761e1/Tuerkiyede-Vergi-Harcamalarinin-Gelisimi-ve-Gelir-Kaybi-Acisindan-Degerlendirilmesi-2006-2020-Yillari.pdf)
(https://www.sciencedirect.com/science/article/pii/S2212567116300466)
(https://www.sciencedirect.com/science/article/abs/pii/S0047272799000225)
(chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://dergipark.org.tr/en/download/article-file/777910)

